#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 22 17:27:11 WET 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim mat_tb_behav -key {Behavioral:sim_1:Functional:mat_tb} -tclbatch mat_tb.tcl -view /home/gpaiva/dot_product/mat_tb_behav.wcfg -log simulate.log"
xsim mat_tb_behav -key {Behavioral:sim_1:Functional:mat_tb} -tclbatch mat_tb.tcl -view /home/gpaiva/dot_product/mat_tb_behav.wcfg -log simulate.log

